#ifndef MAIN_H
#define MAIN_H
#define MAX_STUDENTID_LENGTH 256
#define MAX_UIMENU_SELECTION_LENGTH 7
#define MAX_FILENAME_LENGTH 256
#define MAX_ROWS 100
#define MAX_COLS 100
#define END_PROGRAM_KEYWORD "-quit"
#endif